# Generated by Django 5.1.4 on 2024-12-28 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                ("rate_count", models.IntegerField(default=0)),
                ("rate", models.FloatField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["pub_date", "id"], name="posts_post_pub_dat_cce227_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PostRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                ("rate", models.SmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("post", "user_id"), name="unique_user_post_rate"
                    )
                ],
            },
        ),
    ]
